-- 010-relax-external-id-columns-to-text.sql
-- Fix: tenant-facing identifier columns were typed UUID, but external systems
-- (including dev-auth demo tenants) produce non-UUID string identifiers like
-- 'tu-demo-alice', 'unit-101', 'prop-unit-101'. Postgres rejects these as
-- invalid UUID syntax, causing 500 errors on conversation creation.
--
-- Strategy (plan option A3 — Hybrid):
--   - External identifiers (tenant_user_id, tenant_account_id, unit_id,
--     property_id, client_id) -> TEXT. These come from tenant/ERP systems
--     whose ID format we do not control.
--   - Internal identifiers (conversation_id, event_id, work_order_id,
--     notification_id, issue_group_id, issue_id, preference_id,
--     incident_id) -> remain UUID. These are generated by randomUUID().

-- sessions (003)
ALTER TABLE sessions
  ALTER COLUMN tenant_user_id TYPE TEXT;

-- work_orders (004)
ALTER TABLE work_orders
  ALTER COLUMN client_id TYPE TEXT,
  ALTER COLUMN property_id TYPE TEXT,
  ALTER COLUMN unit_id TYPE TEXT,
  ALTER COLUMN tenant_user_id TYPE TEXT,
  ALTER COLUMN tenant_account_id TYPE TEXT;

-- notification_events (002)
ALTER TABLE notification_events
  ALTER COLUMN tenant_user_id TYPE TEXT,
  ALTER COLUMN tenant_account_id TYPE TEXT;

-- notification_preferences (006)
ALTER TABLE notification_preferences
  ALTER COLUMN tenant_account_id TYPE TEXT;
